### ISSUE TITLE
bkg-image no proper height on mobile phone

### ISSUE THREAD

**Issue by Allmedialab** [ThemeMountain/pine#20] opened 2018-01-29 13:22 UTC
Hi,

First of all thanks for this beautiful  email framework!

Did run some tests and when I insert the bkg-image.html code  in the boiler page the height of the background image is lost on smaller screens. Even in a browser when you narrow the mail the height seems
to change drastically on smaller screens. Is this a error or part of the design?

Regards & Thanks,

David

**Comment by cossssmin** [comment] 2018-01-29 14:37
Hi David, and thanks for the kind words.

Indeed, this is by design. We're using the [Universal Spacer](https://thememountain.github.io/pine/components/spacer.html#universal) to set the height of this module and, as you can see from the docs I linked to, spacers are reset to 30px high on mobile, for consistent vertical spacing.

However, as it's mentioned there, you can override this with an inline `height:` CSS. For reference, here's our example from the docs:

`<div class="spacer" style="line-height: 80px; height: 80px;">&nbsp;</div>`

In this case, using `height: 80px;` will force the spacer to stay at 80px high even on mobile.

So in the case of the background image example, you'd do this:

```
<table align="center" cellpadding="0" cellspacing="0" role="presentation" width="100%">
  <tr>
    <td class="col px-sm-2" width="100%" bgcolor="#1F2225" background="https://picsum.photos/700/500?image=307" style="background-image: url('https://picsum.photos/700/500?image=307'); background-repeat: no-repeat; background-position: center; background-size: cover;">
      <!--[if gte mso 9]>
      <v:image src="https://picsum.photos/700/500?image=307" xmlns:v="urn:schemas-microsoft-com:vml" style="width:700px;height:500px;" />
      <v:rect fill="true" stroke="false" style="position:absolute;width:700px;height:500px;">
      <v:fill opacity="0">
      <div>
      <![endif]-->
      <div class="spacer" style="line-height: 213px; height: 213px;">&nbsp;</div>
      <h1 style="color: #FFFFFF; font-size: 40px; font-weight: 300; line-height: 40px; margin: 0 0 10px; text-align: center;">Overlayed Text</h1>
      <div style="color: #FFFFFF; text-align: center;">CAN BE ANY HTML YOU NEED</div>
      <div class="spacer" style="line-height: 213px; height: 213px;">&nbsp;</div>
      <!--[if gte mso 9]></div></v:fill></v:rect><![endif]-->
    </td>
  </tr>
</table>
```

Cheers,
Cosmin

**Comment by Allmedialab** [comment] 2018-01-29 15:02
OK now I understand!
Thanks,
David

**Comment by cossssmin** [comment] 2018-01-29 15:12
You're welcome, I'll go ahead and close the issue.

**Closed as completed by cossssmin** 2018-01-29 15:12 UTC
